version: '3.8'

services:
  # Microserviço Users
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: fiap-users
    environment:
      # Usando Oracle da FIAP
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      SPRING_DATASOURCE_USERNAME: rm552975
      SPRING_DATASOURCE_PASSWORD: 260899
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Definindo dialeto explicitamente
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.Oracle12cDialect
      # Especificando driver explicitamente
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - fiap-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Microserviço Sprinkler
  sprinkler:
    build:
      context: ./sprinkler
      dockerfile: Dockerfile
    container_name: fiap-sprinkler
    environment:
      # Usando Oracle da FIAP
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      SPRING_DATASOURCE_USERNAME: rm552975
      SPRING_DATASOURCE_PASSWORD: 260899
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Definindo dialeto explicitamente
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.Oracle12cDialect
      # Especificando driver explicitamente
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - fiap-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

# Definição de rede
networks:
  fiap-network:
    driver: bridge
