services:
  # Nota: O banco de dados Oracle é fornecido pela FIAP e não precisa ser executado localmente

  # Microserviço Users
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: fiap-users-prod
    environment:
      # Usando perfil de produção
      SPRING_PROFILES_ACTIVE: prod
      # Credenciais do Oracle já configuradas no application-prod.properties
      JWT_SECRET: minha-chave-secreta-de-producao-muito-longa-e-segura
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - fiap-network-prod

  # Microserviço Sprinkler
  sprinkler:
    build:
      context: ./sprinkler
      dockerfile: Dockerfile
    container_name: fiap-sprinkler-prod
    environment:
      # Usando perfil de produção
      SPRING_PROFILES_ACTIVE: prod
      # Credenciais do Oracle já configuradas no application-prod.properties
      JWT_SECRET: minha-chave-secreta-de-producao-muito-longa-e-segura
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      users:
        condition: service_started
    networks:
      - fiap-network-prod

networks:
  fiap-network-prod:
    driver: bridge
