--CREATE TABLE tbl_sprinkler (
--    ID INT AUTO_INCREMENT PRIMARY KEY,
--    USER_ID INT,
--    LOCATION VARCHAR(255) NOT NULL,
--    STATUS VARCHAR(255),
--    OPERATION_MODE VARCHAR(255),
--    NAME VARCHAR(255),
--    CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES tbl_user(id)
--);

CREATE TABLE tbl_sprinkler (
    ID INT PRIMARY KEY,
    USER_ID INT,
    LOCATION VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(255),
    OPERATION_MODE VARCHAR2(255),
    NAME VARCHAR2(255),
    CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES tbl_user(id)
);