--CREATE TABLE tbl_user (
--    ID INT AUTO_INCREMENT PRIMARY KEY,
--    NAME VARCHAR(255) NOT NULL,
--    PASSWORD VARCHAR(255) NOT NULL,
--    EMAIL VARCHAR(255) NOT NULL UNIQUE,
--    ROLE VARCHAR(255) NOT NULL
--);

CREATE TABLE tbl_user (
    ID INT PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    ROLE VARCHAR2(255) NOT NULL
);