apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: cm9vdA== # root em base64
  password: aXBtc3VwMTQy # ipmsup142 em base64

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  jwt-secret: bXktc2VjcmV0LWtleQ== # my-secret-key em base64
