name: CD - Deploy para Staging e Produção

on:
  workflow_run:
    workflows: ["CI - Compilação e Testes"]
    branches: [develop, main, master]
    types:
      - completed

jobs:
  deploy-to-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Deploy para o ambiente de Staging
        run: |
          echo "Imagens Docker para Staging foram publicadas com sucesso no Docker Hub:"
          echo "  - ${{ secrets.DOCKER_HUB_USERNAME }}/fiap-users:staging"
          echo "  - ${{ secrets.DOCKER_HUB_USERNAME }}/fiap-users:staging-${{ github.event.workflow_run.head_sha }}"
          echo "  - ${{ secrets.DOCKER_HUB_USERNAME }}/fiap-sprinkler:staging"
          echo "  - ${{ secrets.DOCKER_HUB_USERNAME }}/fiap-sprinkler:staging-${{ github.event.workflow_run.head_sha }}"
          echo "Para executar localmente, use: docker-compose -f docker-compose-staging.yml up -d"
          
          # Exemplo de comando para deploy remoto (comentado):
          # ssh ${{ secrets.STAGING_SERVER_USER }}@${{ secrets.STAGING_SERVER_HOST }} \
          #   "cd /path/to/app && \
          #   export DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }} && \
          #   export IMAGE_TAG=staging && \
          #   docker-compose -f docker-compose-staging.yml pull && \
          #   docker-compose -f docker-compose-staging.yml up -d"

  deploy-to-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'master') }}
    runs-on: ubuntu-latest
    environment: production
    needs: []  # Sem dependências diretas, pois depende da condição if
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Deploy para o ambiente de Produção
        run: |
          echo "Imagens Docker para Produção foram publicadas com sucesso no Docker Hub:"
          echo "  - ${{ secrets.DOCKER_HUB_USERNAME }}/fiap-users:prod"
          echo "  - ${{ secrets.DOCKER_HUB_USERNAME }}/fiap-users:prod-${{ github.event.workflow_run.head_sha }}"
          echo "  - ${{ secrets.DOCKER_HUB_USERNAME }}/fiap-sprinkler:prod"
          echo "  - ${{ secrets.DOCKER_HUB_USERNAME }}/fiap-sprinkler:prod-${{ github.event.workflow_run.head_sha }}"
          echo "Para executar localmente, use: docker-compose -f docker-compose-prod.yml up -d"
          
          # Exemplo de comando para deploy remoto (comentado):
          # ssh ${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_HOST }} \
          #   "cd /path/to/app && \
          #   export DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }} && \
          #   export IMAGE_TAG=prod && \
          #   docker-compose -f docker-compose-prod.yml pull && \
          #   docker-compose -f docker-compose-prod.yml up -d"
