name: Testes BDD e Deploy - Pipeline Completa

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, develop, master ]
  workflow_dispatch:

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # --- Testes Users ------------------------------------------------------
      - name: Executar testes BDD – Users
        id: users-tests
        working-directory: ./users
        run: |
          ./mvnw -B clean test \
            -Dtest=br.com.fiap.users.bdd.CucumberRunnerTest \
            -Dcucumber.features=src/test/resources/features \
            -Dcucumber.glue=br.com.fiap.users.bdd.steps,br.com.fiap.users.bdd.config
          # Se der erro, o próprio exit‑code do Maven aborta o job

      # --- Testes Sprinkler (só se Users passou) -----------------------------
      - name: Executar testes BDD – Sprinkler
        if: steps.users-tests.outcome == 'success'
        working-directory: ./sprinkler
        run: |
          ./mvnw -B clean test \
            -Dtest=br.com.fiap.aspersor.bdd.CucumberRunnerTest \
            -Dcucumber.features=src/test/resources/features \
            -Dcucumber.glue=br.com.fiap.aspersor.bdd.steps,br.com.fiap.aspersor.bdd

      # --- Relatórios (sempre, para ter logs) -------------------------------
      - name: Publicar relatórios
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-testes
          path: |
            **/target/cucumber-reports
            **/target/surefire-reports
          retention-days: 7

  # --------------------------------------------------------------------------
  deploy:
    needs: testes
    if: needs.testes.result == 'success'      # só se todos os testes passaram
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Deploy – Users
        working-directory: ./users
        run: ./mvnw -B clean package -DskipTests

      - name: Deploy – Sprinkler
        working-directory: ./sprinkler
        run: ./mvnw -B clean package -DskipTests
