name: Testes BDD Simples

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, develop, master ]
  # Possibilidade de execução manual
  workflow_dispatch:

jobs:
  testes:
    name: Executar Testes BDD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Executar todos os testes BDD no microsserviço Users
      - name: Executar testes BDD - Users
        working-directory: ./users
        run: ./mvnw test -Dtest=**/bdd/CucumberRunnerTest

      # Executar todos os testes BDD no microsserviço Sprinkler
      - name: Executar testes BDD - Sprinkler
        working-directory: ./sprinkler
        run: ./mvnw test -Dtest=**/bdd/CucumberRunnerTest

      # Publicar relatórios como artefatos
      - name: Publicar relatórios
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-testes
          path: |
            **/target/cucumber-reports
            **/target/surefire-reports
          retention-days: 7